POST http://localhost:5000/auth/register
Content-Type: application/json

{
  "username": "Bhuvan",
  "email": "bhuvan@gmail.com",
  "phonenumber": 1234567890,
  "password": "Bhuvan123",
  "role": "admin"
}

###

POST http://localhost:5000/auth/login
Content-Type: application/json

{
  "email": "bhuvan@gmail.com",
  "password": "Bhuvan123"
}
