### Register a new admin user
POST http://localhost:5000/auth/register
Content-Type: application/json

{
  "username": "Bhuvan",
  "email": "bhuvan@gmail.com",
  "phonenumber": 1234567890,
  "password": "Bhuvan123",
  "role": "admin"
}

### Register a new basic user
POST http://localhost:5000/auth/register
Content-Type: application/json

{
  "username": "Chethan",
  "email": "chethan@gmail.com",
  "phonenumber": 7894561230,
  "password": "Chethan123",
  "role": "basic"
}

### Admin user login
POST http://localhost:5000/auth/login
Content-Type: application/json

{
  "email": "bhuvan@gmail.com",
  "password": "Bhuvan123"
}

### Basic user login
POST http://localhost:5000/auth/login
Content-Type: application/json

{
  "email": "chethan@gmail.com",
  "password": "Chethan123"
}