### Add Restaurant (Admin)
POST http://localhost:5000/restaurant/addrestaurant
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3N2QxNzdiOTU4NTdhNWIxOGU2OWVhNCIsInVzZXJuYW1lIjoiQmh1dmFuIiwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzM2MzE5NzgxLCJleHAiOjE3MzYzMjMzODF9.0CjABxIt-QFkt6gTU3VEbD6Dz3cmHYfHZiTLveD1Wjs

{
  "restaurant": "Madhuvana Cafe",
  "cuisine": "Cafe",
  "rating": 4,
  "area": "677e234187f304dd40a3f44d"
}

###

GET http://localhost:5000/restaurant/677e23a687f304dd40a3f452
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3N2QxNzdiOTU4NTdhNWIxOGU2OWVhNCIsInVzZXJuYW1lIjoiQmh1dmFuIiwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzM2MzE5NzgxLCJleHAiOjE3MzYzMjMzODF9.0CjABxIt-QFkt6gTU3VEbD6Dz3cmHYfHZiTLveD1Wjs

