POST http://localhost:5000/review/addreview
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3N2QxNzdiOTU4NTdhNWIxOGU2OWVhNCIsInVzZXJuYW1lIjoiQmh1dmFuIiwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzM2MzE5NzgxLCJleHAiOjE3MzYzMjMzODF9.0CjABxIt-QFkt6gTU3VEbD6Dz3cmHYfHZiTLveD1Wjs
Content-Type: application/json

{
    "userId": "677d177b95857a5b18e69ea4",
  "restaurantId": "677e23a687f304dd40a3f452",
  "rating": 3,
  "comment": "Quite expensive!"
}

###

DELETE http://localhost:5000/review/deletereview/677e03bfde1696a6dce87bc3
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3N2QxNzdiOTU4NTdhNWIxOGU2OWVhNCIsInVzZXJuYW1lIjoiQmh1dmFuIiwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzM2MzEwMTc1LCJleHAiOjE3MzYzMTM3NzV9.eDHjBo5eLwckWzQCVnTM3SCLtLqQLOzwzE_qbC85EYo
Content-Type: application/json

{
  "userId": "677d177b95857a5b18e69ea4"
}